site_name: Predicting NBA Wins
docs_dir: 'docs'
nav:
  - Home: "index.md"
  - Analytics explained:
    - "Per game stats explained": analytics/per-game.md
    - "Per 100 possesions stats explained": analytics/per-100-possesions.md
    - "Season total stats explained": analytics/season-totals.md
    - "Advanced stats explained": analytics/advanced.md
  - Datasets:
    - "External data": datasets/external.md
    - "Raw data": datasets/raw.md
    - "Interim data": datasets/interim.md
    - "Processed data": datasets/processed.md
  - Reports:
    - "Predicting wins using advanced stats": reports/advanced.md
    - "Predicting wins using per 100 possesions stats": reports/per-100-possesions.md
    - "Predicting wins using per game stats": reports/per-game.md
    - "Predicting wins using season total stats": reports/season-totals.md
  - Conclusion: "conclusion.md"
theme:
  name: material
  logo: https://1000marcas.net/wp-content/uploads/2019/12/NBA-Logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - header.autohide
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
