site_name: Predicting NBA Wins
docs_dir: 'docs'
nav:
  - Home: "index.md"
  - The datasets used:
    - "Advanced stats dataset": datasets/advanced.md
    - "Per game stats dataset": datasets/per-game.md
    - "Per 100 possesions stats dataset": datasets/per-100-possesions.md
    - "Season total stats dataset": datasets/season-totals.md
  - Assumptions: "assumptions.md"
  - Analytics explained:
    - "Basic stats": analytics/basic-stats.md
    - "Advanced stats": analytics/advanced-stats.md
  - Data pipeline:
    - "External data": data-states/external.md
    - "Raw data": data-states/raw.md
    - "Interim data": data-states/interim.md
    - "Processed data": data-states/processed.md
  - Reports:
    - "Predicting wins using advanced stats": reports/advanced.md
    - "Predicting wins using per 100 possesions stats": reports/per-100-possesions.md
    - "Predicting wins using per game stats": reports/per-game.md
    - "Predicting wins using season total stats": reports/season-totals.md
  - Conclusion: "conclusion.md"
theme:
  name: material
  logo: https://1000marcas.net/wp-content/uploads/2019/12/NBA-Logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
